# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)

        self.btn_load_image = QtWidgets.QPushButton(Dialog)
        self.btn_load_image.setGeometry(QtCore.QRect(50, 30, 200, 40))
        self.btn_load_image.setObjectName("btn_load_image")

        self.btn_preprocess = QtWidgets.QPushButton(Dialog)
        self.btn_preprocess.setGeometry(QtCore.QRect(50, 80, 200, 40))
        self.btn_preprocess.setObjectName("btn_preprocess")

        self.btn_extract_features = QtWidgets.QPushButton(Dialog)
        self.btn_extract_features.setGeometry(QtCore.QRect(50, 130, 200, 40))
        self.btn_extract_features.setObjectName("btn_extract_features")

        self.btn_build_index = QtWidgets.QPushButton(Dialog)
        self.btn_build_index.setGeometry(QtCore.QRect(50, 180, 200, 40))
        self.btn_build_index.setObjectName("btn_build_index")

        self.btn_query_image = QtWidgets.QPushButton(Dialog)
        self.btn_query_image.setGeometry(QtCore.QRect(50, 230, 200, 40))
        self.btn_query_image.setObjectName("btn_query_image")

        self.btn_show_topk = QtWidgets.QPushButton(Dialog)
        self.btn_show_topk.setGeometry(QtCore.QRect(50, 280, 200, 40))
        self.btn_show_topk.setObjectName("btn_show_topk")

        self.btn_metrics = QtWidgets.QPushButton(Dialog)
        self.btn_metrics.setGeometry(QtCore.QRect(50, 330, 200, 40))
        self.btn_metrics.setObjectName("btn_metrics")

        self.btn_vit_evaluation = QtWidgets.QPushButton(Dialog)
        self.btn_vit_evaluation.setGeometry(QtCore.QRect(50, 380, 200, 40))
        self.btn_vit_evaluation.setObjectName("btn_vit_evaluation")

        # Textinput
        self.input_text_query = QtWidgets.QLineEdit(Dialog)
        self.input_text_query.setGeometry(QtCore.QRect(50, 430, 240, 30))
        self.input_text_query.setPlaceholderText("Digite sua busca textual...")

        # Button to search by text
        self.btn_text_search = QtWidgets.QPushButton(Dialog)
        self.btn_text_search.setGeometry(QtCore.QRect(50, 470, 200, 40))
        self.btn_text_search.setObjectName("btn_text_search")

        self.btn_text_visualize = QtWidgets.QPushButton(Dialog)
        self.btn_text_visualize.setGeometry(QtCore.QRect(50, 510, 200, 40))
        self.btn_text_visualize.setObjectName("btn_text_visualize")

        self.log_output = QtWidgets.QTextBrowser(Dialog)
        self.log_output.setGeometry(QtCore.QRect(300, 300, 660, 250))
        self.log_output.setObjectName("log_output")

        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(300, 30, 660, 250))
        self.image_label.setObjectName("image_label")
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Image Retrieval Interface"))
        self.btn_load_image.setText(_translate("Dialog", "Load image"))
        self.btn_preprocess.setText(_translate("Dialog", "Pre process the image"))
        self.btn_extract_features.setText(_translate("Dialog", "Extract features"))
        self.btn_build_index.setText(_translate("Dialog", "Build the index"))
        self.btn_query_image.setText(_translate("Dialog", "Check images"))
        self.btn_show_topk.setText(_translate("Dialog", "Show Top-k"))
        self.btn_metrics.setText(_translate("Dialog", "Evaluate metrics"))
        self.btn_vit_evaluation.setText(_translate("Dialog", "Evaluate with ViT"))
        self.btn_text_search.setText(_translate("Dialog", "Search with text"))
        self.btn_text_visualize.setText(_translate("Dialog", "Show text results"))
